server:
  port: ${PORT:8081}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
    metadata-map:
       app-owner: mrodriguezul
       description: microservicio productos
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mtproductos?serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
